- name: configure firewall rules
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  vars:
    base_dir: "/home/{{ssh_user}}"
  tasks:
#---------------------------------------------------------------------------------------------
  - name: "ufw default deny incoming"
    become: true
    become_method: sudo
    command: "ufw default deny incoming"
    when: config_firewall == 1
#---------------------------------------------------------------------------------------------
  - name: "ufw default allow outgoing"
    become: true
    become_method: sudo
    command: "ufw default allow outgoing"
    when: config_firewall == 1
#---------------------------------------------------------------------------------------------
  - name: "ufw allow everything for network: '{{network_cidr}}'"
    become: true
    become_method: sudo
    command: "ufw allow from {{network_cidr}}"
    when: config_firewall == 1
#---------------------------------------------------------------------------------------------
  - name: enable the firewall
    become: true
    become_method: sudo
    ufw:
      state: enabled
    when: config_firewall == 1
