- name: create portainer stack for mosquitto mqtt
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  vars:
    stack_name: "mqtt"
  tasks:
#---------------------------------------------------------------------------------------------
  - name: "authenticate with portainer api"
    uri:
      url: "{{portainer_host}}/api/auth"
      method: POST
      headers:
        Content-Type: "application/json"
      body_format: json
      body:
        username: "{{ portainer_user }}"
        password: "{{ portainer_pass }}"
    register: auth_response
    changed_when: false
    ignore_errors: true
#---------------------------------------------------------------------------------------------
  - name: "check authentication response"
    fail:
      msg: "failed to authenticate with portainer api"
    when: "auth_response.status != 200"
#---------------------------------------------------------------------------------------------
  - name: "get jwt token from authentication response"
    set_fact:
      jwt_token: "{{auth_response.json.jwt}}"
    when: auth_response.status == 200
#---------------------------------------------------------------------------------------------
  - name: "get endpoints from portainer"
    uri:
      url: "{{portainer_host}}/api/endpoints"
      method: GET
      headers:
        Authorization: "Bearer {{jwt_token}}"
    register: get_endpoints
    when: jwt_token is defined
#---------------------------------------------------------------------------------------------
  - name: 'checking if portainer is initialized correctly'
    fail:
      msg: "portainer seems to be freshly installed, please login manually once at: http://{{ansible_host}}:9000 and after that execute this script again."
    when: jwt_token is defined and not get_endpoints.json is search("Id")
#---------------------------------------------------------------------------------------------
  - name: "get stack information from portainer"
    uri:
      url: "{{portainer_host}}/api/stacks"
      method: GET
      headers:
        Authorization: "Bearer {{jwt_token}}"
    register: get_stack_response
    when: jwt_token is defined
#---------------------------------------------------------------------------------------------
  - name: "check if the stack exists"
    set_fact:
      stack_not_exists: "{{response_data | json_query('[?Name == `'+ stack_name +'`]') | length <= 0}}"
    vars:
      response_data: "{{get_stack_response.json}}"
#---------------------------------------------------------------------------------------------
  - name: "setup folder for container data"
    file:
      path: "{{DATA_DIRECTORY}}/{{stack_name}}/data"
      state: directory
      owner: "{{ssh_user}}"
      group: "{{ssh_user}}"
      mode: '0755'
    when: jwt_token is defined and stack_not_exists
    ignore_errors: true
#---------------------------------------------------------------------------------------------
  - name: "setup folder for container config"
    file:
      path: "{{DATA_DIRECTORY}}/{{stack_name}}/config"
      state: directory
      owner: "{{ssh_user}}"
      group: "{{ssh_user}}"
      mode: '0755'
    when: jwt_token is defined and stack_not_exists
    ignore_errors: true
#---------------------------------------------------------------------------------------------
  - name: checking if '{{DATA_DIRECTORY}}/{{stack_name}}/config/mosquitto.conf' exists
    stat:
      path: "{{DATA_DIRECTORY}}/{{stack_name}}/config/mosquitto.conf"
    register: has_config
    when: stack_not_exists
#---------------------------------------------------------------------------------------------
  - name: "create mosquitto.conf"
    command: "touch {{DATA_DIRECTORY}}/{{stack_name}}/config/mosquitto.conf"
    when: stack_not_exists and not has_config.stat.exists
#---------------------------------------------------------------------------------------------
  - name: write mosquitto default config
    blockinfile:
      state: present
      insertafter: EOF
      dest: "{{DATA_DIRECTORY}}/{{stack_name}}/config/mosquitto.conf"
      marker: "#<!-- mosquitto default -->"
      content: |
        # following two lines required for > v2.0
        allow_anonymous true
        listener 1883
        persistence true
        persistence_location /mosquitto/data/
        log_dest file /mosquitto/log/mosquitto.log
    when: stack_not_exists
#---------------------------------------------------------------------------------------------
  - name: "create a stack in portainer"
    uri:
      url: "{{portainer_host}}/api/stacks/create/standalone/string?endpointId={{get_endpoints.json[0].Id}}"
      method: POST
      headers:
        Content-Type: "application/json"
        Authorization: "Bearer {{jwt_token}}"
      body_format: json
      body:
        name: "{{stack_name}}"
        fromAppTemplate: false
        StackFileContent: |
          version: '3'
          networks:
            home:
              external: true
          services:
            {{stack_name}}:
              restart: unless-stopped
              container_name: {{stack_name}}
              image: eclipse-mosquitto:2
              user: mosquitto
              volumes:
                - {{DATA_DIRECTORY}}/{{stack_name}}/config:/mosquitto/config
                - {{DATA_DIRECTORY}}/{{stack_name}}/data:/mosquitto/data
              ports:
                - 1883:1883
              labels:
                - homepage.group=Backend
                - homepage.name=Mosquitto
                - homepage.icon=mqtt.png
                - homepage.description=MQTT Broker
                - traefik.enable=false
              networks:
                - home
    register: create_stack_response
    when: jwt_token is defined and stack_not_exists
#---------------------------------------------------------------------------------------------
