- name: install zerotier
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  tasks:
#---------------------------------------------------------------------------------------------
  - name: ensure curl is at the latest version
    become: true
    become_method: sudo
    apt:
      name: curl
      state: latest
#---------------------------------------------------------------------------------------------
  - name: download zerotier installer
    command: "curl -s https://install.zerotier.com"
    register: zerotier_install_script
#---------------------------------------------------------------------------------------------
  - name: copy installer content to file
    copy: content="{{zerotier_install_script.stdout}}" dest=/home/{{ssh_user}}/install_zerotier.sh
#---------------------------------------------------------------------------------------------
  - name: make '/home/{{ssh_user}}/install_zerotier.sh' executable
    command: "chmod +x /home/{{ssh_user}}/install_zerotier.sh"
#---------------------------------------------------------------------------------------------
  - name: install zerotier
    become: true
    become_method: sudo
    command: "./install_zerotier.sh"
    args:
      chdir: "/home/{{ssh_user}}"
