- name: install docker with compose plugin
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  tasks:
  - name: upgrade installed apt packages
    become: true
    become_method: sudo
    apt:
      name: "*"
      state: latest
      update_cache: yes
      cache_valid_time: 30 #One day 
    when: install_docker == 1
#---------------------------------------------------------------------------------------------
  - name: ensure 'ca-certificates' is at the latest version
    become: true
    become_method: sudo
    apt:
      name: ca-certificates
      state: latest
    when: install_docker == 1
#---------------------------------------------------------------------------------------------
  - name: ensure 'curl' is at the latest version
    become: true
    become_method: sudo
    apt:
      name: curl
      state: latest
    when: install_docker == 1
#---------------------------------------------------------------------------------------------
  - name: "install /etc/apt/keyrings"
    become: true
    become_method: sudo
    command: install -m 0755 -d /etc/apt/keyrings
    when: install_docker == 1
#---------------------------------------------------------------------------------------------
  - name: "downloading docker gpg key to '/etc/apt/keyrings/docker.asc'"
    become: true
    become_method: sudo
    command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    when: install_docker == 1
#---------------------------------------------------------------------------------------------
  - name: "setting permission '/etc/apt/keyrings/docker.asc'"
    become: true
    become_method: sudo
    command: chmod a+r /etc/apt/keyrings/docker.asc
#---------------------------------------------------------------------------------------------
  - name: setup docker repository
    become: true
    become_method: sudo
    copy: content="deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu   oracular stable" dest=/etc/apt/sources.list.d/docker.list
#---------------------------------------------------------------------------------------------
  - name: update package repository
    become: true
    become_method: sudo
    command: apt update
#---------------------------------------------------------------------------------------------
  - name: ensure docker-ce is at the latest version
    become: true
    become_method: sudo
    ansible.builtin.apt:
      name: docker-ce
      state: latest
#---------------------------------------------------------------------------------------------
  - name: ensure docker-ce-cli is at the latest version
    become: true
    become_method: sudo
    ansible.builtin.apt:
      name: docker-ce-cli
      state: latest
#---------------------------------------------------------------------------------------------
  - name: ensure containerd.io is at the latest version
    become: true
    become_method: sudo
    ansible.builtin.apt:
      name: containerd.io
      state: latest
#---------------------------------------------------------------------------------------------
  - name: ensure docker-buildx-plugin is at the latest version
    become: true
    become_method: sudo
    ansible.builtin.apt:
      name: docker-buildx-plugin
      state: latest
#---------------------------------------------------------------------------------------------
  - name: ensure docker-compose-plugin is at the latest version
    become: true
    become_method: sudo
    ansible.builtin.apt:
      name: docker-compose-plugin
      state: latest
#---------------------------------------------------------------------------------------------
  - name: "add docker group"
    become: true
    become_method: sudo
    command: groupadd docker
    ignore_errors: True
#---------------------------------------------------------------------------------------------
  - name: "add current user to docker group"
    become: true
    become_method: sudo
    command: "usermod -aG docker {{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "create 'home' network for docker"
    become: true
    become_method: sudo
    command: docker network create home
    ignore_errors: True
